name: .NET

on:
  push:
    branches: [ "master" ]
    paths-ignore: 
      - '**/README.md'
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '8.0.x'
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      

