name: ReleaseBuild

on:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # setting the dotnet version
  DOTNET_VERSION: '8.0.x'

permissions:
  id-token: write # Required for NuGet trusted publishing (OIDC)
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # gets the current commmit
    - uses: actions/checkout@v4

    # installs the dotnet command line tool
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
      # Restore nuget packages
    - name: Restore dependencies
      run: dotnet restore
      
      # build the source
    - name: Build
      run: dotnet build --no-restore --configuration Release      
      
      # Run the unit tests
    - name: Unit Tests
      run: dotnet test --no-build --verbosity normal --configuration Release
      
      # Obtain a short-lived NuGet API key via OIDC trusted publishing
    - name: NuGet login
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}

      # Publish the Nuget file to Nuget.org
    - name: PushNuget
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate
